-- Vendor & AP Spend Analytics — synthetic dataset schema
-- ------------------------------------------------------------------
-- Mirrors a representative slice of a Unit4 / Coda-style ERP used by an
-- academic health system for accounts payable + vendor management. Table
-- and column names follow the real ERP (oas_element, oas_grplist,
-- oas_dochead, oas_docline) so the analysis SQL reads authentically.
--
-- DATA IS SYNTHETIC — generated by generate_data.py and calibrated to
-- realistic AP distributions (Pareto vendor spend, master-data hygiene,
-- payment timing). NO real vendor names, dollar figures, or PII appear,
-- because production financial data is confidential. Two legal entities
-- are modeled via cmpcode: 'MSO' (medical service org) and 'FDN' (foundation).
-- ------------------------------------------------------------------

DROP TABLE IF EXISTS oas_element;
DROP TABLE IF EXISTS oas_grplist;
DROP TABLE IF EXISTS oas_dochead;
DROP TABLE IF EXISTS oas_docline;
DROP TABLE IF EXISTS dim_division;

-- Element master: vendors (elmlevel=3) and divisions (elmlevel=2).
-- One row per (cmpcode, code) — a vendor registered in both entities has two rows.
CREATE TABLE oas_element (
  cmpcode    TEXT    NOT NULL,          -- legal entity: 'MSO' | 'FDN'
  code       TEXT    NOT NULL,          -- vendor 'V0001' (elmlevel 3) | division '1200' (elmlevel 2)
  name       TEXT    NOT NULL,          -- full vendor/division name
  sname      TEXT,                      -- short name
  elmlevel   INTEGER NOT NULL,          -- 3 = vendor, 2 = division
  adddate    TEXT,                      -- record onboarded (ISO date)
  deldate    TEXT,                      -- deactivation date (blank if open)
  endperiod  INTEGER NOT NULL DEFAULT 0,-- closing fiscal period (0 = open)
  endyear    INTEGER NOT NULL DEFAULT 0,-- closing fiscal year   (0 = open; nonzero = CLOSED in this entity)
  country    TEXT,                      -- vendor address country ('USA' domestic; else foreign)
  defaddr    INTEGER NOT NULL DEFAULT 0,-- 1 = default (primary) address row
  PRIMARY KEY (cmpcode, code)
);

-- Group membership: every vendor carries an 'XDEPT' group plus a category group
-- (PHARMA, MEDDEV, LABSUP, ITSVC, FACIL, PROSVC, STAFFNG, OFFICE, TRAVEL, UTIL).
CREATE TABLE oas_grplist (
  cmpcode   TEXT    NOT NULL,
  code      TEXT    NOT NULL,           -- vendor code
  elmlevel  INTEGER NOT NULL,           -- 3 = vendor
  grpcode   TEXT    NOT NULL            -- 'XDEPT' | category group code
);

-- AP document header: one row per posted AP document.
CREATE TABLE oas_dochead (
  cmpcode   TEXT    NOT NULL,
  docnum    INTEGER NOT NULL,
  yr        INTEGER NOT NULL,           -- fiscal year (FY starts in July)
  period    INTEGER NOT NULL,           -- fiscal period 1..12
  doccode   TEXT    NOT NULL,           -- 'API' invoice | 'APC' credit/adjustment
  adddate   TEXT    NOT NULL,           -- date document entered (ISO date)
  PRIMARY KEY (cmpcode, docnum)
);

-- AP document lines: the transactional grain.
CREATE TABLE oas_docline (
  cmpcode   TEXT    NOT NULL,
  docnum    INTEGER NOT NULL,
  el3       TEXT    NOT NULL,           -- vendor code   (joins oas_element.code where elmlevel=3)
  el2       TEXT    NOT NULL,           -- division code (joins oas_element.code where elmlevel=2)
  valuedoc  REAL    NOT NULL,           -- line amount in document currency (credits negative)
  statpay   INTEGER NOT NULL,          -- 89 = paid; 0 = open/unpaid
  paydate   TEXT                        -- payment date (blank if unpaid)
);

-- Convenience dimension (NOT in the real ERP): generic division -> department map,
-- so BI tools and readers can roll divisions up to clinical/finance departments.
CREATE TABLE dim_division (
  division_code TEXT NOT NULL,
  department    TEXT NOT NULL
);

-- Helpful indexes for the analysis queries.
CREATE INDEX idx_docline_el3   ON oas_docline (el3);
CREATE INDEX idx_docline_pay   ON oas_docline (statpay);
CREATE INDEX idx_dochead_doc   ON oas_dochead (cmpcode, docnum);
CREATE INDEX idx_element_lvl   ON oas_element (elmlevel, endyear);
